# Generated by Django 6.0.7 on 2026-07-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
            options={
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('equipment_name', models.CharField(max_length=150)),
                ('equipment_type', models.CharField(choices=[('VENTILATOR', 'Ventilator'), ('INFUSION_PUMP', 'Infusion Pump'), ('ECG_MACHINE', 'ECG Machine'), ('PATIENT_MONITOR', 'Patient Monitor'), ('WHEELCHAIR', 'Wheelchair'), ('DEFIBRILLATOR', 'Defibrillator'), ('OXYGEN_CONCENTRATOR', 'Oxygen Concentrator'), ('HOSPITAL_BED', 'Hospital Bed')], max_length=30)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_due', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('FAULTY', 'Faulty'), ('DECOMMISSIONED', 'Decommissioned')], default='AVAILABLE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='equipment.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='equipment.equipmentcategory')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='equipment.vendor')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['-created_at'],
            },
        ),
    ]
