# Generated by Django 6.0.7 on 2026-07-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_designation_staff'),
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='wards.ward'),
        ),
    ]
