# Generated by Django 6.0.7 on 2026-08-01 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be 9-15 digits, optionally starting with '+'.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
