# Generated by Django 6.0.7 on 2026-07-29 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('wards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('RETURNED', 'Returned')], default='ALLOCATED', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='equipment.equipment')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='wards.ward')),
            ],
            options={
                'ordering': ['-allocated_date'],
            },
        ),
    ]
